name: Build

on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout notepad++
        uses: actions/checkout@v4
        with:
          repository: notepad-plus-plus/notepad-plus-plus
          ref: refs/tags/v8.6.9
          path: notepad++

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0
          vsversion: 2019

      - name: Build notepad++.exe
        working-directory: notepad++/PowerEditor/visual.net
        run: |
          ls
          msbuild notepadPlus.sln /p:Platform=x64 /p:Configuration=Release /p:WholeProgramOptimization=true

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: notepad++
          path: |
            notepad++/PowerEditor/bin64/*.exe
            notepad++/PowerEditor/bin64/*.dll
